### ISSUE TITLE
help with wasp setup

### ISSUE THREAD

**Issue by aSTUDYofSELF** [thiago-goncalves-souza/zootraits#11]
hi, just getting into programming, running into the following error when wanting to create new app.

<img width="625" alt="SCR-20240412-uhuu-2" src="https://github.com/thiago-goncalves-souza/zootraits/assets/166868338/98d1f59e-e0b4-439f-809b-763b8ff8fc23">

**Comment by beatrizmilz** [comment]
Hi @aSTUDYofSELF !
This is not the best place to ask for help. 
This repository is related to a Shiny App, and the issues of this repository should be to write about bugs/questions/improvements of this app.


You can try Stackoverflow for general questions.
Another tip is to have a real name and real photo in your profile. Without this information, the chances you get a valuable response is short.

Related to the question: based on the picture, it seems like you don't have Node installed (if you use Brew, see: https://formulae.brew.sh/formula/node ; if you don't,  brew is great for installing libraries on Mac).
